import {
  siAngular,
  siAxios,
  siBootstrap,
  siClaude,
  siCss,
  siDatadog,
  siDocker,
  siExpress,
  siFastify,
  siFigma,
  siGit,
  siGithub,
  siGithubactions,
  siGithubcopilot,
  siGitlab,
  siGooglecloud,
  siHtml5,
  siJest,
  siKibana,
  siModelcontextprotocol,
  siMongodb,
  siMui,
  siN8n,
  siNestjs,
  siNextdotjs,
  siNodedotjs,
  siNuxt,
  siOpencode,
  siPostgresql,
  siPostman,
  siReactivex,
  siReact,
  siSass,
  siStorybook,
  siStrapi,
  siSwagger,
  siTailwindcss,
  siTypescript,
  siJavascript,
  siVite,
  siVuedotjs,
  type SimpleIcon,
} from 'simple-icons';

/** Brand marks from Simple Icons (CC0), drawn single-color in the channel. */
export const ICONS: Record<string, SimpleIcon> = {
  ts: siTypescript,
  js: siJavascript,
  react: siReact,
  next: siNextdotjs,
  tailwind: siTailwindcss,
  bootstrap: siBootstrap,
  mui: siMui,
  html: siHtml5,
  css: siCss,
  sass: siSass,
  vite: siVite,
  vue: siVuedotjs,
  nuxt: siNuxt,
  angular: siAngular,
  nest: siNestjs,
  node: siNodedotjs,
  strapi: siStrapi,
  express: siExpress,
  fastify: siFastify,
  jest: siJest,
  rxjs: siReactivex,
  axios: siAxios,
  swagger: siSwagger,
  mongodb: siMongodb,
  postgresql: siPostgresql,
  'claude-code': siClaude,
  opencode: siOpencode,
  copilot: siGithubcopilot,
  mcp: siModelcontextprotocol,
  n8n: siN8n,
  git: siGit,
  github: siGithub,
  gitlab: siGitlab,
  storybook: siStorybook,
  figma: siFigma,
  postman: siPostman,
  docker: siDocker,
  'github-actions': siGithubactions,
  gcp: siGooglecloud,
  datadog: siDatadog,
  kibana: siKibana,
};

/**
 * The marks are served as one static sprite (app/stack-icons.svg) and drawn
 * with <use>, so their ~55 KB of path data stays out of the page's HTML and
 * RSC payload; the plate is far below the fold, so the extra request is free.
 */
export const STACK_SPRITE = '/stack-icons.svg';

export const stackSprite = () =>
  `<svg xmlns="http://www.w3.org/2000/svg">${Object.entries(ICONS)
    .map(([id, icon]) => `<symbol id="${id}" viewBox="0 0 24 24"><path d="${icon.path}"/></symbol>`)
    .join('')}</svg>`;
