export { default as Navbar } from './Navbar';
export { default as Header } from './Header';
export { default as AboutMe } from './AboutMe';
export { default as Projects } from './Projects';
export { default as Architecture } from './Architecture';
export { default as AiProfile } from './AiProfile';
export { default as Skills } from './Skills';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
